config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  resources :posts
  root 'posts#index'

  resources :sessions, except: [:index, :show, :edit, :update]

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :name, presence: true
	validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, presence: true, uniqueness: true
	#user.authentication("password")
	#nambahin 2, password dan password_confirmation
	#nambahin validasi password dan password_confirmation

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :current_user

  def current_user
  	@current_user = if params[:token]
      User.find_by(auth_token: params[:token])
    else 
      User.find(session[:user_id]) if session[:user_id]
    end
  end
  def authorize
  	respond_to do |format|
      format.html {redirect_to new_session_path, alert: "Unauthorized" unless current_user}
      format.json { render json: "token salah" unless current_user}
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authorize, except: [:index, :show]
	def index
		@post = Post.all
		respond_to do |format|
			format.html
			format.json {render json: @post}
		end
	end
	def new 
		@post = Post.new		
	end
	def create
		@post = Post.new(params.require(:post).permit(:name, :latitude, :longitude))
		if @post.save
			redirect_to root_path, notice: "Success"
		else
			render :new
		end
	end
	def edit
		@post = Post.find(params[:id])
	end
	def update
		@post = Post.find(params[:id])
		@post.update(params.require(:post).permit(:name, :longitude, :latitude))
		redirect_to posts_path
	end
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
  		respond_to do |format|
  			format.html { redirect_to root_path, notice: 'Model was successfully destroyed' }
  			format.json { head :no_content }
  		end
	end
	def show
		@post = Post.find(params[:id])
		respond_to do |format|
			format.html
			format.json {render json: @post}
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end
	def create
		#1. GET USER BASED EMAIL
		#2. JIKA USER ADA OTENTIFIKASI DENGAN PASSWORD YANG DI SUBMIT
		#3. HANDLE RESPONS
		user = User.find_by(email: params[:email])
		respond_to do |format|
		if user && user.authenticate(params[:password])
			format.html do 
			#login success
			session[:user_id] = user.id
			redirect_to posts_path, notice: "Logged In!"
		end
		format.json {render json: user}
	else
		format.html do 
			flash.now.alert = "Invalid email or password"
			render :new
		end
		format.json {render json: "Invalid email or password"}
	end
end
end
def destroy
	session[:user_id] = nil
	redirect_to posts_path, notice: "Success Logged Out"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	def create
		@user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, notice: "Successfully create user"
		else
			render :new
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Maps</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active">
        <a href="#">Hello, <%= current_user ? current_user.email : 'Guest' %></a>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <% if current_user %>
      <li><%= link_to "Log Out", session_path(current_user), method: 'delete' %></li>
      <% else %>
      <li><%= link_to "Login", new_session_path %></li>
      <li><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
    </ul>
  </section>
</nav>
<% if  notice %>
<div data-alert class="alert-box success radius">
  <%= notice %>
  <a href="#" class="close">&times;</a>
</div>
<% end %>
  <% if  alert %>
<div data-alert class="alert-box alert radius">
  <%= alert %>
  <a href="#" class="close">&times;</a>
</div>
<% end %>


    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Places</h1>
<%= form_for @post do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :latitude %>
	<%= f.text_field :latitude %>
	<br>
	<%= f.label :longitude %>
	<%= f.text_field :longitude %>
	<br>
	<%= f.submit 'Update', class: 'button radius small' %>
	<% end %>

app/views/posts/index.html.erb
<h1>List Places</h1>
<table>
	<tr>
		<th>Name</th>
		<th>Longitude</th>
		<th>Latitude</th>
	</tr>
<% @post.each do |f| %>
<tr>
	<td><%= f.name %></td>
	<td><%= f.latitude %></td>
	<td><%= f.longitude %></td>
	<td><%= link_to 'show', post_path(f) %></td>
	<td><%= link_to 'edit', edit_post_path(f)%></td>
	<td><%= link_to 'delete', post_path(f), method: 'delete' %>
</td>
</tr>
<% end %>
</table>
<%= link_to 'Input Lokasi', new_post_path %>

app/views/posts/new.html.erb
<h1>New Places</h1>
<% if !@post.errors.empty? %>
	<% @post.errors.full_messages.each do |error| %>
		<h4 style="color:red;"><%= error %></h4>
	<%end %>
	<% end %>
<%= form_for @post do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :latitude %>
	<%= f.text_field :latitude %>
	<br>
	<%= f.label :longitude %>
	<%= f.text_field :longitude %>
	<br>
	<%= f.submit %>
	<% end %>

app/views/posts/show.html.erb
<h1><%= @post.name %></h1>
<p>Latitude : <%= @post.latitude %> </p>
<p>Longitude : <%= @post.longitude %> </p>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x200&sensor=false&zoom=168markers=#{@post.
	latitude}%2C#{@post.longitude }" %>
<p><%= link_to 'Back to Home', root_path %></p>

app/views/users/new.html.erb
<h1>New User</h1>
<% if !@user.errors.empty? %>
	<% @user.errors.full_messages.each do |error| %>
		<h4 style="color:red;"><%= error %></h4>
	<%end %>
	<% end %>
<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.email_field :email %>
	<br>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<br>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<br>
	<%= f.submit 'Submit', class: 'button radius small' %>
	<% end %>